export const QUERY_KEY = {
    CART: 'CART',
    PRODUCTS: 'products',
    CATEGORIES: 'categories',
    LATEST: 'latest',
    DEALS: 'deals',
    REVIEWS: 'review',
    RELATED: 'related',
    POPULARCATEGORIES: 'poularCategories',
    BRANDS: 'brands',
    MY_ORDERS: 'myOrders',
    ORDERS: 'orders',
    CHECKOUT: 'checkout',
    ATTRIBUTES: 'attributes',
};
